import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Fraunces, Open_Sans } from "next/font/google";
import SearchField from "./components/SearchField";
import Navbar from "@/app/components/Navbar";
import Footer from "./components/Footer";
import SocialMediaIcons from "./components/SocialMediaIcons";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./admin/Providers";

const fraunces = Fraunces({
  subsets: ["latin"],
  weight: ["100", "400", "700"], // normal weights
  style: ["normal", "italic"], // include italic if available
  display: "swap",
  variable: "--font-fraunces",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // You can add "300", "600", etc.
  display: "swap",
  variable: "--font-open-sans",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fraunces.variable} ${openSans.variable} bg-white`}
    >
      <Providers>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* <SearchField /> */}
          <Navbar />
          <SocialMediaIcons />
          {children}
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
